# Generated by Django 4.2.13 on 2024-05-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='Address',
            field=models.CharField(default='تهران - برج میلاد', max_length=500),
        ),
        migrations.CreateModel(
            name='timeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDateTime', models.DateTimeField()),
                ('Seat', models.IntegerField()),
                ('concertModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.concertmodel')),
                ('locationModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.locationmodel')),
            ],
        ),
    ]
