# Generated by Django 4.2.13 on 2024-05-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0004_concertmodel_poster_ticketmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmodel',
            old_name='ProfilrModel',
            new_name='ProfileModel',
        ),
    ]
