# Generated by Django 4.2.13 on 2024-05-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0005_rename_profilrmodel_ticketmodel_profilemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertmodel',
            options={'verbose_name': 'مدل کنسرت', 'verbose_name_plural': 'مدل کنسرت'},
        ),
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name': 'مکان', 'verbose_name_plural': 'مکان ها'},
        ),
        migrations.AlterModelOptions(
            name='ticketmodel',
            options={'verbose_name': 'بلیت', 'verbose_name_plural': 'بلیت ها'},
        ),
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name': 'سانس', 'verbose_name_plural': 'سانس ها'},
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام کنسرت'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Poster',
            field=models.ImageField(upload_to='concertImages/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='SingerName',
            field=models.CharField(max_length=100, verbose_name='نام خواننده'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='lenght',
            field=models.IntegerField(verbose_name='طول برنامه'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Address',
            field=models.CharField(default='تهران - برج میلاد', max_length=500, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام محل'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Phone',
            field=models.CharField(max_length=11, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='capacity',
            field=models.IntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام بلیت'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Price',
            field=models.IntegerField(verbose_name='بهای بلیت'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticketImage',
            field=models.ImageField(upload_to='TicketImages/', verbose_name='تصویر بلیت'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Seat',
            field=models.IntegerField(verbose_name='شماره صندلی'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='StartDateTime',
            field=models.DateTimeField(verbose_name='تایم شروع'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Status',
            field=models.IntegerField(choices=[(1, 'فروش بلیط آغاز شده است'), (2, 'پایان'), (4, 'در حال فروش...'), (3, 'کنسل شده')], default=1, verbose_name='وضعیت'),
        ),
    ]
